services:
  - type: web
    name: financial-data-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: financial-data-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: financial-data-redis
          type: redis
          property: connectionString

databases:
  - name: financial-data-db
    databaseName: financial_data
    user: financial_user          

redis:
  - name: financial-data-redis